CREATE TABLE etf (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker          VARCHAR(10)  NOT NULL UNIQUE,
    name            VARCHAR(200) NOT NULL,
    expense_ratio   NUMERIC(6,4),
    inception_date  DATE,
    is_castellan    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE holding (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etf_id              BIGINT       NOT NULL REFERENCES etf(id),
    as_of_date          DATE         NOT NULL,
    security_type       VARCHAR(10)  NOT NULL,
    instrument_symbol   VARCHAR(40)  NOT NULL,
    underlying_ticker   VARCHAR(10),
    shares              NUMERIC(20,6),
    market_value        NUMERIC(20,2),
    weight_pct          NUMERIC(9,4),
    notional_value      NUMERIC(20,2),
    CONSTRAINT uk_holding UNIQUE (etf_id, as_of_date, instrument_symbol)
);

CREATE INDEX idx_holding_etf_date ON holding(etf_id, as_of_date);
CREATE INDEX idx_holding_underlying ON holding(underlying_ticker);

CREATE TABLE price_bar (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      VARCHAR(10)  NOT NULL,
    bar_date    DATE         NOT NULL,
    open_px     NUMERIC(14,4),
    high_px     NUMERIC(14,4),
    low_px      NUMERIC(14,4),
    close_px    NUMERIC(14,4) NOT NULL,
    adj_close   NUMERIC(14,4),
    volume      BIGINT,
    CONSTRAINT uk_price UNIQUE (ticker, bar_date)
);

CREATE INDEX idx_price_ticker_date ON price_bar(ticker, bar_date);

CREATE TABLE etl_run (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name    VARCHAR(50)  NOT NULL,
    started_at  TIMESTAMP    NOT NULL,
    finished_at TIMESTAMP,
    status      VARCHAR(20)  NOT NULL,
    rows_in     INTEGER,
    rows_out    INTEGER,
    error_msg   VARCHAR(2000)
);

CREATE INDEX idx_etl_run_job_started ON etl_run(job_name, started_at DESC);
