CREATE TABLE option_contract (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    underlying_ticker   VARCHAR(10)  NOT NULL,
    expiration          DATE         NOT NULL,
    strike              NUMERIC(14,4) NOT NULL,
    option_type         VARCHAR(4)   NOT NULL,
    contract_size       INTEGER      NOT NULL DEFAULT 100,
    is_flex             BOOLEAN      NOT NULL DEFAULT FALSE,
    description         VARCHAR(200),
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_option_contract UNIQUE (underlying_ticker, expiration, strike, option_type)
);

CREATE INDEX idx_option_underlying ON option_contract(underlying_ticker);
CREATE INDEX idx_option_expiration ON option_contract(expiration);

ALTER TABLE holding ADD COLUMN option_contract_id BIGINT;
ALTER TABLE holding ADD CONSTRAINT fk_holding_option
    FOREIGN KEY (option_contract_id) REFERENCES option_contract(id);

CREATE INDEX idx_holding_option ON holding(option_contract_id);
